// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FuneralHomeWebApi.Data.DbModels
{
    [Index("KorisnikId", Name = "IX_Osiguranje", IsUnique = true)]
    public partial class Osiguranje
    {
        [Key]
        public int Id { get; set; }
        public int KorisnikId { get; set; }
        public DateTime DatumUgovaranja { get; set; }
        //public DateOnly DatumUgovaranja { get; set; }
        public bool PlacanjeNaRate { get; set; }

        public virtual Korisnik Korisnik { get; set; }
    }
}