// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using FuneralHome.DataAccess.SqlServer.Data.DbModels;

namespace FuneralHome.DataAccess.SqlServer.Data
{
    public partial class FuneralHomeContext : DbContext
    {
        public FuneralHomeContext()
        {
        }

        public FuneralHomeContext(DbContextOptions<FuneralHomeContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Cvijece> Cvijece { get; set; }
        public virtual DbSet<Glazba> Glazba { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<Lijes> Lijes { get; set; }
        public virtual DbSet<NadgrobniZnak> NadgrobniZnak { get; set; }
        public virtual DbSet<Oglas> Oglas { get; set; }
        public virtual DbSet<Osiguranje> Osiguranje { get; set; }
        public virtual DbSet<Osmrtnica> Osmrtnica { get; set; }
        public virtual DbSet<Pogreb> Pogreb { get; set; }
        public virtual DbSet<SmrtniSlucaj> SmrtniSlucaj { get; set; }
        public virtual DbSet<Urna> Urna { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Korisnik>(entity =>
            {
                entity.Property(e => e.VrstaKorisnika).IsFixedLength();
            });

            modelBuilder.Entity<Oglas>(entity =>
            {
                entity.HasOne(d => d.Osmrtnica)
                    .WithMany(p => p.Oglas)
                    .HasForeignKey(d => d.OsmrtnicaId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Oglas_Osmrtnica");

                entity.HasOne(d => d.SmrtniSlucaj)
                    .WithOne(p => p.Oglas)
                    .HasForeignKey<Oglas>(d => d.SmrtniSlucajId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Oglas_SmrtniSlucaj");
            });

            modelBuilder.Entity<Osiguranje>(entity =>
            {
                entity.HasOne(d => d.Korisnik)
                    .WithOne(p => p.Osiguranje)
                    .HasForeignKey<Osiguranje>(d => d.KorisnikId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Osiguranje_Korisnik");
            });

            modelBuilder.Entity<Pogreb>(entity =>
            {
                entity.HasOne(d => d.Cvijece)
                    .WithMany(p => p.Pogreb)
                    .HasForeignKey(d => d.CvijeceId)
                    .HasConstraintName("FK_Pogreb_Cvijece");

                entity.HasOne(d => d.Glazba)
                    .WithMany(p => p.Pogreb)
                    .HasForeignKey(d => d.GlazbaId)
                    .HasConstraintName("FK_Pogreb_Glazba");

                entity.HasOne(d => d.Lijes)
                    .WithMany(p => p.Pogreb)
                    .HasForeignKey(d => d.LijesId)
                    .HasConstraintName("FK_Pogreb_Lijes");

                entity.HasOne(d => d.NadgrobniZnak)
                    .WithMany(p => p.Pogreb)
                    .HasForeignKey(d => d.NadgrobniZnakId)
                    .HasConstraintName("FK_Pogreb_NadgrobniZnak");

                entity.HasOne(d => d.SmrtniSlucaj)
                    .WithOne(p => p.Pogreb)
                    .HasForeignKey<Pogreb>(d => d.SmrtniSlucajId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Pogreb_SmrtniSlucaj");

                entity.HasOne(d => d.Urna)
                    .WithMany(p => p.Pogreb)
                    .HasForeignKey(d => d.UrnaId)
                    .HasConstraintName("FK_Pogreb_Urna");
            });

            modelBuilder.Entity<SmrtniSlucaj>(entity =>
            {
                entity.HasOne(d => d.Korisnik)
                    .WithMany(p => p.SmrtniSlucaj)
                    .HasForeignKey(d => d.KorisnikId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_SmrtniSlucaj_Korisnik");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}