// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using FuneralHome.DataAccess.SqlServer.Data.DbModels;

namespace FuneralHome.DataAccess.SqlServer.Data
{
    public partial class FuneralHomeContext : DbContext
    {
        public FuneralHomeContext()
        {
        }

        public FuneralHomeContext(DbContextOptions<FuneralHomeContext> options)
            : base(options)
        {
        }

        public virtual DbSet<JedinicaMjere> JedinicaMjere { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<Kupnja> Kupnja { get; set; }
        public virtual DbSet<KupnjaOpremaUsluge> KupnjaOpremaUsluge { get; set; }
        public virtual DbSet<OpremaUsluga> OpremaUsluga { get; set; }
        public virtual DbSet<Osiguranje> Osiguranje { get; set; }
        public virtual DbSet<PaketOsiguranja> PaketOsiguranja { get; set; }
        public virtual DbSet<Pogreb> Pogreb { get; set; }
        public virtual DbSet<PogrebOpremaUsluge> PogrebOpremaUsluge { get; set; }
        public virtual DbSet<SmrtniSlucaj> SmrtniSlucaj { get; set; }
        public virtual DbSet<VrstaOpremeUsluge> VrstaOpremeUsluge { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Korisnik>(entity =>
            {
                entity.Property(e => e.Oib).IsFixedLength();

                entity.Property(e => e.VrstaKorisnika).IsFixedLength();
            });

            modelBuilder.Entity<Kupnja>(entity =>
            {
                entity.HasOne(d => d.Korisnik)
                    .WithMany(p => p.Kupnja)
                    .HasForeignKey(d => d.KorisnikId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Kupnja_Korisnik");
            });

            modelBuilder.Entity<KupnjaOpremaUsluge>(entity =>
            {
                entity.HasKey(e => new { e.KupnjaId, e.OpremaUslugaId })
                    .HasName("PK_KupnjaOpremaUsluge_1");

                entity.HasOne(d => d.Kupnja)
                    .WithMany(p => p.KupnjaOpremaUsluge)
                    .HasForeignKey(d => d.KupnjaId)
                    .HasConstraintName("FK_KupnjaOpremaUsluge_Kupnja");

                entity.HasOne(d => d.OpremaUsluga)
                    .WithMany(p => p.KupnjaOpremaUsluge)
                    .HasForeignKey(d => d.OpremaUslugaId)
                    .HasConstraintName("FK_KupnjaOpremaUsluge_OpremaUsluga");
            });

            modelBuilder.Entity<OpremaUsluga>(entity =>
            {
                entity.HasKey(e => e.IdOpremaUsluga)
                    .HasName("PK_Oprema");

                entity.HasOne(d => d.VrstaOpremeUsluge)
                    .WithMany(p => p.OpremaUsluga)
                    .HasForeignKey(d => d.VrstaOpremeUslugeId)
                    .HasConstraintName("FK_Oprema_VrstaOpreme");
            });

            modelBuilder.Entity<Osiguranje>(entity =>
            {
                entity.HasOne(d => d.Korisnik)
                    .WithOne(p => p.Osiguranje)
                    .HasForeignKey<Osiguranje>(d => d.KorisnikId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Osiguranje_Korisnik");

                entity.HasOne(d => d.PaketOsiguranja)
                    .WithMany(p => p.Osiguranje)
                    .HasForeignKey(d => d.PaketOsiguranjaId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Osiguranje_PaketOsiguranja1");
            });

            modelBuilder.Entity<Pogreb>(entity =>
            {
                entity.HasOne(d => d.SmrtniSlucaj)
                    .WithOne(p => p.Pogreb)
                    .HasForeignKey<Pogreb>(d => d.SmrtniSlucajId)
                    .HasConstraintName("FK_Pogreb_SmrtniSlucaj");
            });

            modelBuilder.Entity<PogrebOpremaUsluge>(entity =>
            {
                entity.HasKey(e => new { e.PogrebId, e.OpremaUslugaId })
                    .HasName("PK_PogrebOprema");

                entity.HasOne(d => d.OpremaUsluga)
                    .WithMany(p => p.PogrebOpremaUsluge)
                    .HasForeignKey(d => d.OpremaUslugaId)
                    .HasConstraintName("FK_PogrebOprema_Oprema");

                entity.HasOne(d => d.Pogreb)
                    .WithMany(p => p.PogrebOpremaUsluge)
                    .HasForeignKey(d => d.PogrebId)
                    .HasConstraintName("FK_PogrebOprema_Pogreb");
            });

            modelBuilder.Entity<SmrtniSlucaj>(entity =>
            {
                entity.Property(e => e.Oibpok).IsFixedLength();

                entity.HasOne(d => d.Korisnik)
                    .WithMany(p => p.SmrtniSlucaj)
                    .HasForeignKey(d => d.KorisnikId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_SmrtniSlucaj_Korisnik");
            });

            modelBuilder.Entity<VrstaOpremeUsluge>(entity =>
            {
                entity.HasKey(e => e.IdVrstaOpremeUsluge)
                    .HasName("PK_VrstaOpreme");

                entity.HasOne(d => d.JedinicaMjere)
                    .WithMany(p => p.VrstaOpremeUsluge)
                    .HasForeignKey(d => d.JedinicaMjereId)
                    .HasConstraintName("FK_VrstaOpremeUsluge_JedinicaMjere");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}