// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FuneralHome.DataAccess.SqlServer.Data.DbModels
{
    public partial class Kupnja
    {
        public Kupnja()
        {
            KupnjaOpremaUsluge = new HashSet<KupnjaOpremaUsluge>();
        }

        [Key]
        public int IdKupnja { get; set; }
        public int KorisnikId { get; set; }
        public DateTime DatumKupovine { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal UkupnaCijena { get; set; }

        [ForeignKey("KorisnikId")]
        [InverseProperty("Kupnja")]
        public virtual Korisnik Korisnik { get; set; }
        [InverseProperty("Kupnja")]
        public virtual ICollection<KupnjaOpremaUsluge> KupnjaOpremaUsluge { get; set; }
    }
}