// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FuneralHome.DataAccess.SqlServer.Data.DbModels
{
    public partial class KupnjaOpremaUsluge
    {
        [Key]
        public int KupnjaId { get; set; }
        [Key]
        public int OpremaUslugaId { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal Kolicina { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal Cijena { get; set; }

        [ForeignKey("KupnjaId")]
        [InverseProperty("KupnjaOpremaUsluge")]
        public virtual Kupnja Kupnja { get; set; }
        [ForeignKey("OpremaUslugaId")]
        [InverseProperty("KupnjaOpremaUsluge")]
        public virtual OpremaUsluga OpremaUsluga { get; set; }
    }
}