// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FuneralHome.DataAccess.SqlServer.Data.DbModels
{
    [Index("PaketOsiguranjaId", Name = "IX_Osiguranje", IsUnique = true)]
    [Index("KorisnikId", Name = "IX_Osiguranje_1", IsUnique = true)]
    public partial class Osiguranje
    {
        [Key]
        public int IdOsiguranje { get; set; }
        public int KorisnikId { get; set; }
        public DateTime DatumUgovaranja { get; set; }
        public bool PlacanjeNaRate { get; set; }
        public int? BrojRata { get; set; }
        public int PaketOsiguranjaId { get; set; }

        [ForeignKey("KorisnikId")]
        [InverseProperty("Osiguranje")]
        public virtual Korisnik Korisnik { get; set; }
        [ForeignKey("PaketOsiguranjaId")]
        [InverseProperty("Osiguranje")]
        public virtual PaketOsiguranja PaketOsiguranja { get; set; }
    }
}