// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FuneralHome.DataAccess.SqlServer.Data.DbModels
{
    public partial class PogrebOpremaUsluge
    {
        [Key]
        public int PogrebId { get; set; }
        [Key]
        public int OpremaUslugaId { get; set; }
        public int Kolicina { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal Cijena { get; set; }

        [ForeignKey("OpremaUslugaId")]
        [InverseProperty("PogrebOpremaUsluge")]
        public virtual OpremaUsluga OpremaUsluga { get; set; }
        [ForeignKey("PogrebId")]
        [InverseProperty("PogrebOpremaUsluge")]
        public virtual Pogreb Pogreb { get; set; }
    }
}