// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FuneralHome.DataAccess.SqlServer.Data.DbModels
{
    [Index("SmrtniSlucajId", Name = "IX_Pogreb", IsUnique = true)]
    public partial class Pogreb
    {
        public Pogreb()
        {
            PogrebOprema = new HashSet<PogrebOprema>();
            Usluga = new HashSet<Usluga>();
        }

        [Key]
        public int IdPogreb { get; set; }
        public int SmrtniSlucajId { get; set; }
        public DateTime DatumPogreb { get; set; }
        public bool Kremacija { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal Cijena { get; set; }

        [ForeignKey("SmrtniSlucajId")]
        [InverseProperty("Pogreb")]
        public virtual SmrtniSlucaj SmrtniSlucaj { get; set; }
        [InverseProperty("Pogreb")]
        public virtual ICollection<PogrebOprema> PogrebOprema { get; set; }

        [ForeignKey("PogrebId")]
        [InverseProperty("Pogreb")]
        public virtual ICollection<Usluga> Usluga { get; set; }
    }
}