// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FuneralHome.DataAccess.SqlServer.Data.DbModels
{
    [Index("Oibpok", Name = "IX_PrijavaSmrtnogSlucaja_OIB", IsUnique = true)]
    public partial class SmrtniSlucaj
    {
        [Key]
        public int Id { get; set; }
        public int KorisnikId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string ImePok { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string PrezimePok { get; set; }
        [Column("OIBPok")]
        public int Oibpok { get; set; }
        //public DateOnly DatumRodenjaPok { get; set; }
        //public DateOnly DatumSmrtiPok { get; set; }
        public DateTime DatumRodenjaPok { get; set; }
        public DateTime DatumSmrtiPok { get; set; }

        [ForeignKey("KorisnikId")]
        [InverseProperty("SmrtniSlucaj")]
        public virtual Korisnik Korisnik { get; set; }
        [InverseProperty("SmrtniSlucaj")]
        public virtual Oglas Oglas { get; set; }
        [InverseProperty("SmrtniSlucaj")]
        public virtual Pogreb Pogreb { get; set; }
    }
}