// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FuneralHome.DataAccess.SqlServer.Data.DbModels
{
    public partial class Urna
    {
        public Urna()
        {
            Pogreb = new HashSet<Pogreb>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public byte[] Naziv { get; set; }
        public byte[] Slika { get; set; }
        public int Kolicina { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal Cijena { get; set; }

        [InverseProperty("Urna")]
        public virtual ICollection<Pogreb> Pogreb { get; set; }
    }
}