// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FuneralHome.DataAccess.SqlServer.Data.DbModels
{
    public partial class Usluga
    {
        public Usluga()
        {
            Pogreb = new HashSet<Pogreb>();
        }

        [Key]
        public int IdUsluga { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Naziv { get; set; }
        public int VrstaUslugeId { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Opis { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal Cijena { get; set; }

        [ForeignKey("VrstaUslugeId")]
        [InverseProperty("Usluga")]
        public virtual VrstaUsluge VrstaUsluge { get; set; }

        [ForeignKey("UslugaId")]
        [InverseProperty("Usluga")]
        public virtual ICollection<Pogreb> Pogreb { get; set; }
    }
}