// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FuneralHome.DataAccess.SqlServer.Data.DbModels
{
    public partial class VrstaUsluge
    {
        public VrstaUsluge()
        {
            Usluga = new HashSet<Usluga>();
        }

        [Key]
        public int IdVrstaUsluge { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Naziv { get; set; }

        [InverseProperty("VrstaUsluge")]
        public virtual ICollection<Usluga> Usluga { get; set; }
    }
}